# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-04 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190104_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='hows_book',
            field=models.ManyToManyField(to='polls.Books'),
        ),
    ]
