# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180131_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationswithbooks',
            name='books_author',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operationswithbooks',
            name='books_class',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operationswithbooks',
            name='books_nameIzd',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operationswithbooks',
            name='books_numIzd',
            field=models.CharField(default=5, max_length=200),
            preserve_default=False,
        ),
    ]
