# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-12 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190112_1859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books_model',
        ),
    ]
