# Generated by Django 2.0.1 on 2018-02-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180211_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='_class',
            new_name='clas',
        ),
    ]
