# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180212_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('clas_of_user', models.CharField(max_length=200, verbose_name='Класс учащихся')),
                ('numIzd', models.CharField(max_length=200, verbose_name='Номер издания')),
                ('nameIzd', models.CharField(max_length=200, verbose_name='Название издания')),
                ('pub_date', models.DateField(verbose_name='Дата выдачи')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='AddBooks',
        ),
    ]
