# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-05 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190205_0954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthModel',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='NewUser',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='TypeBook',
        ),
        migrations.RemoveField(
            model_name='user_give_book',
            name='given_book',
        ),
        migrations.RemoveField(
            model_name='userprofile1',
            name='hows_book',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='User_Give_Book',
        ),
        migrations.DeleteModel(
            name='UserProfile1',
        ),
    ]
