# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180212_1819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddBooks',
            new_name='Books',
        ),
        migrations.DeleteModel(
            name='GiveBooks',
        ),
    ]
