# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180212_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='borrover',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Books', verbose_name='hello'),
        ),
    ]
