# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_books_borrover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='borrover',
        ),
        migrations.AddField(
            model_name='books',
            name='borrower',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Books', verbose_name='Выдать книгу'),
        ),
    ]
