# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-13 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20190213_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='type_of_book',
            field=models.IntegerField(choices=[(1, 'Учебник'), (2, 'Художественная литература')], default=1),
        ),
    ]
