# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20180220_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='nameIzd',
            new_name='name_izd',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='numIzd',
            new_name='num_izd',
        ),
        migrations.AlterField(
            model_name='books',
            name='borrower',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Выдать книгу'),
        ),
    ]
