# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-02 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_books_type_of_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='give_date',
        ),
        migrations.RemoveField(
            model_name='books',
            name='pass_date',
        ),
        migrations.AlterField(
            model_name='books',
            name='type_of_book',
            field=models.IntegerField(choices=[(1, 'Учебник'), (2, 'Художественная литература')], default=1, verbose_name='Вид книги'),
        ),
    ]
