# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-31 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20180222_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество книг'),
            preserve_default=False,
        ),
    ]
