# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-05 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20190302_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Количество книг'),
        ),
    ]
