# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-18 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='Имя')),
                ('fename', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('third_name', models.CharField(max_length=200, verbose_name='Отчество')),
                ('clas', models.CharField(max_length=200, verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
    ]
