# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-26 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20190326_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Заголовок новости')),
                ('text_of_news', models.CharField(max_length=200, null=True, verbose_name='Текс новости')),
                ('data_pub', models.DateField(null=True, verbose_name='Дата публикации новости')),
            ],
        ),
    ]
