# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-30 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20181130_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='which_book',
        ),
        migrations.AddField(
            model_name='user',
            name='media_choice',
            field=models.CharField(choices=[('1', 'Magazine'), ('2', 'Radio Station'), ('3', 'Journal'), ('4', 'TV Station'), ('5', 'Newspaper'), ('6', 'Website')], default=0, max_length=25, verbose_name='Выдать ученику'),
            preserve_default=False,
        ),
    ]
