# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-30 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20181130_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='media_choice',
            new_name='which_book',
        ),
    ]
