# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-30 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20181130_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='which_book',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Books', verbose_name='Выдать ученику'),
        ),
    ]
