# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-01 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20181130_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hows_book',
        ),
        migrations.AddField(
            model_name='user',
            name='choice',
            field=models.ManyToManyField(to='polls.Books'),
        ),
    ]
