# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-01 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import mysite.polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20181201_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='choice',
        ),
        migrations.AddField(
            model_name='user',
            name='choice',
            field=models.NullBooleanField(default=None, verbose_name=mysite.polls.models.Books),
        ),
    ]
