# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-01 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_auto_20181201_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hows_book',
        ),
        migrations.AddField(
            model_name='user',
            name='hows_book',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='polls.Books', verbose_name='Выдать ученику'),
        ),
    ]
