# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-06 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20181206_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='c',
            field=models.BooleanField(default=False),
        ),
    ]
