# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-04 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='ЛОГИН')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('clas', models.CharField(max_length=200, verbose_name='Класс')),
                ('num_izd', models.CharField(max_length=200, verbose_name='Номер издания')),
                ('name_izd', models.CharField(max_length=200, verbose_name='Название издания')),
                ('quantity', models.IntegerField(verbose_name='Количество книг')),
                ('status', models.IntegerField(verbose_name='Выдана книга(1) или нет(0)')),
                ('qr_code', models.ImageField(blank=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('third_name', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='Никнейм')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('password_raw', models.CharField(max_length=200, verbose_name='Повторите пароль')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, choices=[(1, 'Встроенная кухня'), (2, 'Кухонная ниша'), (3, 'Кухня-столовая'), (4, 'Кухня-остров'), (5, 'Открытая кухня')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, choices=[(1, 'Учебник'), (2, 'Художественная литература')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Give_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_book', models.ManyToManyField(to='polls.Test')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.IntegerField(blank=True, default=0, null=True, verbose_name='Задолжность')),
                ('hows_book', models.ManyToManyField(blank=True, default=None, null=True, to='polls.Books', verbose_name='Выдать ученику')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='Имя')),
                ('fename', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('third_name', models.CharField(max_length=200, verbose_name='Отчество')),
                ('clas', models.CharField(max_length=200, verbose_name='Класс')),
                ('debt', models.IntegerField(verbose_name='Задолжность')),
                ('hows_book', models.ManyToManyField(to='polls.Books')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
    ]
