# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-12 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_books_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books_model',
            options={'verbose_name': 'Одна Книга', 'verbose_name_plural': 'Одни Книги'},
        ),
        migrations.RemoveField(
            model_name='books',
            name='qr_code',
        ),
    ]
