# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-05 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20190205_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='options',
        ),
    ]
