# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-05 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_userinfo_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='mail',
        ),
    ]
