# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-02 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20190302_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='give_date',
            field=models.DateField(null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='books',
            name='pass_date',
            field=models.DateField(null=True, verbose_name='Дата сдачи'),
        ),
    ]
