# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-26 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20190305_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='quantity',
            field=models.CharField(max_length=200, verbose_name=' ISBN-код'),
        ),
    ]
