# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-15 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(max_length=200, null=True, verbose_name='Ссылка на фон новости'),
        ),
    ]
