# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-15 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_news_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text_of_news',
            field=models.CharField(max_length=200, null=True, verbose_name='Текст новости'),
        ),
    ]
