# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-05 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20190615_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='link',
        ),
        migrations.AlterField(
            model_name='books',
            name='quantity',
            field=models.IntegerField(max_length=200, verbose_name='Количество книг'),
        ),
    ]
