# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-10 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20190805_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexs', models.CharField(max_length=200, verbose_name='Индексы всех книг')),
                ('quantity', models.IntegerField(verbose_name='Количество книг')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('author', models.CharField(max_length=200, verbose_name='Предмет')),
                ('clas', models.CharField(blank=True, default='', max_length=200, verbose_name='Класс')),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество книг'),
        ),
    ]
