# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-10 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20190810_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksgroups',
            name='indexs',
            field=models.CharField(blank=True, max_length=200, verbose_name='Индексы всех книг'),
        ),
    ]
